/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package imatapplication;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Icon;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;


/**
 *
 * @author aleX
 */
public class GridProduct extends javax.swing.JPanel {
    Font f = new Font("Segoe UI Semibold", Font.PLAIN, 20);
    /**
     * Creates new form GridProduct
     */
    public GridProduct(Product p) {
        Product product = p;
        initComponents();
        namn.setFont(f);
        pris.setFont(f);
        enhet.setFont(f);
        namn.setText(p.getName());
        pris.setText(String.format("%s %s", p.getPrice(), p.getUnit()));
        enhet.setText(p.getUnitSuffix());
        Icon icon = IMatDataHandler.getInstance().getImageIcon(p, new Dimension(180,180));
        bild.setIcon(icon);
        antalSpinner.setModel(spinnerFactory(p));
        if(IMatDataHandler.getInstance().isFavorite(p)){
            favorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatapplication/packageApp/images/starYellow.png")));
        } else {
           favorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatapplication/packageApp/images/starWhite.png"))); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namn = new javax.swing.JLabel();
        pris = new javax.swing.JLabel();
        antalSpinner = new javax.swing.JSpinner();
        enhet = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        bild = new javax.swing.JLabel();
        favorit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(150, 300));
        setPreferredSize(new java.awt.Dimension(150, 300));

        namn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        namn.setText("Varunamn");

        pris.setText("Pris/st");

        enhet.setText("st");

        add.setBackground(new java.awt.Color(255, 0, 51));
        add.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Lägg till");
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setDefaultCapable(false);

        bild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        favorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatapplication/packageApp/images/starWhite.png"))); // NOI18N
        favorit.setToolTipText("");
        favorit.setBorderPainted(false);
        favorit.setContentAreaFilled(false);
        favorit.setMaximumSize(new java.awt.Dimension(40, 40));
        favorit.setMinimumSize(new java.awt.Dimension(40, 40));
        favorit.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pris)
                                .addGap(18, 18, 18)
                                .addComponent(antalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enhet)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(favorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(favorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bild, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pris)
                    .addComponent(antalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enhet))
                .addGap(18, 18, 18)
                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JSpinner antalSpinner;
    private javax.swing.JLabel bild;
    private javax.swing.JLabel enhet;
    private javax.swing.JButton favorit;
    private javax.swing.JLabel namn;
    private javax.swing.JLabel pris;
    // End of variables declaration//GEN-END:variables

    private SpinnerModel spinnerFactory(Product p) {
        if(p.getUnitSuffix().equals("kg")){
            return new SpinnerNumberModel(1,1,99,0.1);
        } else {
            return   new SpinnerNumberModel(1,1,99,1);
        }
    }
}
